优化代码

diff --git a/.github/workflows/gki-kernel.yml b/.github/workflows/gki-kernel.yml
--- a/.github/workflows/gki-kernel.yml
+++ b/.github/workflows/gki-kernel.yml
@@ -517,16 +517,49 @@ jobs:
 
             echo "Building the kernel..."
             if [ -f "build/build.sh" ]; then
-              LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC="/usr/bin/ccache clang" || exit 1
+                LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh CC="/usr/bin/ccache clang" || exit 1
             else
-              cd common
-              export PATH="$GITHUB_WORKSPACE/$CONFIG/prebuilts/clang/host/linux-x86/clang-r487747c/bin:$PATH"
-              clang --version
-              export PATH="$GITHUB_WORKSPACE/$CONFIG/gcc/bin:$PATH"
-              gcc -v
-              export PATH="$GITHUB_WORKSPACE/$CONFIG/prebuilts/kernel-build-tools/linux-x86/bin:$PATH"
-              make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang LD=ld.lld HOSTLD=ld.lld gki_defconfig
-              make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang LD=ld.lld HOSTLD=ld.lld
+                case "${{ inputs.kernel_version }}" in
+                    "6.1")
+                        CLANG_VERSION="clang-r487747c"
+                        ;;
+                    "6.6")
+                        CLANG_VERSION="clang-r510928"
+                        ;;
+                    *)
+                        echo "Error: Unsupported kernel_version: '${{ inputs.kernel_version }}'"
+                        exit 1
+                        ;;
+                esac
+
+                echo "Using Clang version: $CLANG_VERSION for Kernel version: ${{ inputs.kernel_version }}"
+
+                cd common
+
+                export PATH="$GITHUB_WORKSPACE/$CONFIG/prebuilts/clang/host/linux-x86/$CLANG_VERSION/bin:$PATH"
+                export PATH="$GITHUB_WORKSPACE/$CONFIG/gcc/bin:$PATH"
+                export PATH="$GITHUB_WORKSPACE/$CONFIG/prebuilts/kernel-build-tools/linux-x86/bin:$PATH"
+
+                echo "--- Clang Version ---"
+                clang --version
+                echo "--- GCC Version ---"
+                aarch64-linux-gnu-gcc -v
+
+                MAKE_PARAMS=(
+                    -j$(nproc --all)
+                    O=out
+                    ARCH=arm64
+                    CROSS_COMPILE=aarch64-linux-gnu-
+                    CC=$CLANG_VERSION
+                    LD=ld.lld
+                    HOSTLD=ld.lld
+                )
+                    
+                echo "--- Running make gki_defconfig ---"
+                make "${MAKE_PARAMS[@]}" gki_defconfig || { echo "make defconfig failed"; exit 1; }
+                    
+                echo "--- Running make ---"
+                make "${MAKE_PARAMS[@]}" || { echo "make failed"; exit 1; }
             fi
             ccache --show-stats
             mkdir -p ../bazel-bin/common/kernel_aarch64/
